name: Compile Examples

on:
  push:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - '.github/workflows/compile_library.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - '.github/workflows/compile_library.yml'

jobs:
  esp8266:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: 
        - "examples/IMAP/Append_Message/Append_Message.ino"
        - "examples/IMAP/Custom_Character_Decoding/Custom_Character_Decoding.ino"
        - "examples/IMAP/Custom_Command/Append_Message/Append_Message.ino"
        - "examples/IMAP/Custom_Command/Idle/Idle.ino"
        - "examples/IMAP/Custom_Command/Basic_Auth/Basic_Auth.ino"
        - "examples/IMAP/Custom_Command/Custom_Auth/Custom_Auth.ino"
        - "examples/IMAP/Namespaces/Namespaces.ino"
        - "examples/IMAP/Get_Quota/Get_Quota.ino"
        - "examples/IMAP/ACL/ACL.ino"
        - "examples/IMAP/DataStreamCallback/DataStreamCallback.ino"
        - "examples/IMAP/Delete_Messages/Delete_Messages_List/Delete_Messages_List.ino"
        - "examples/IMAP/Delete_Messages/Delete_Messages_UIDs_Ranges/Delete_Messages_UIDs_Ranges.ino"
        - "examples/IMAP/Delete_Messages/Delete_Messages_Message_Numbers_Ranges/Delete_Messages_Message_Numbers_Ranges.ino"
        - "examples/IMAP/Copy_Messages/Copy_Messages_List/Copy_Messages_List.ino"
        - "examples/IMAP/Copy_Messages/Copy_Messages_UIDs_Ranges/Copy_Messages_UIDs_Ranges.ino"
        - "examples/IMAP/Copy_Messages/Copy_Messages_Message_Numbers_Ranges/Copy_Messages_Message_Numbers_Ranges.ino"
        - "examples/IMAP/Move_Messages/Move_Messages_List/Move_Messages_List.ino"
        - "examples/IMAP/Move_Messages/Move_Messages_UIDs_Ranges/Move_Messages_UIDs_Ranges.ino"
        - "examples/IMAP/Move_Messages/Move_Messages_Message_Numbers_Ranges/Move_Messages_Message_Numbers_Ranges.ino"
        - "examples/IMAP/Mailbox_Changes_Notification/Mailbox_Changes_Notification.ino"
        - "examples/IMAP/Read_Email_Access_Token/Read_Email_Access_Token.ino"
        - "examples/IMAP/Read_Single_Email/Read_Single_Email.ino"
        - "examples/IMAP/Read_Single_Email_Loop/Read_Single_Email_Loop.ino"
        - "examples/IMAP/Search_Emails/Search_Emails.ino"
        - "examples/IMAP/Set_Flags/Set_Flags_List/Set_Flags_List.ino"
        - "examples/IMAP/Set_Flags/Set_Flags_UIDs_Ranges/Set_Flags_UIDs_Ranges.ino"
        - "examples/IMAP/Set_Flags/Set_Flags_Message_Numbers_Ranges/Set_Flags_Message_Numbers_Ranges.ino"
        - "examples/IMAP/Read_Sequence_Set/Read_Sequence_Set.ino"
        - "examples/SMTP/Ethernet/ESP8266/Send_Text/Send_Text.ino"
        - "examples/SMTP/Reply_Text/Reply_Text.ino"
        - "examples/SMTP/Send_HTML/Send_HTML.ino"
        - "examples/SMTP/Send_Access_Token/Send_Access_Token.ino"
        - "examples/SMTP/Send_Reuse_Session/Send_Reuse_Session.ino"
        - "examples/SMTP/Send_RFC822_Attachment/Send_RFC822_Attachment.ino"
        - "examples/SMTP/Send_Parallel_Attachment/Send_Parallel_Attachment.ino"
        - "examples/SMTP/Send_Attachment_Blob/Send_Attachment_Blob.ino"
        - "examples/SMTP/Send_Flash_Message_with_Inline_Image/Send_Flash_Message_with_Inline_Image.ino"
        - "examples/SMTP/Send_Text/Send_Text.ino"
        - "examples/SMTP/Send_Text_Flowed/Send_Text_Flowed.ino"
        - "examples/SMTP/Send_Enriched_Text/Send_Enriched_Text.ino"
        - "examples/SMTP/Send_Embedded_Message/Send_Embedded_Message.ino"
        - "examples/SMTP/Send_Attachment_File/Send_Attachment_File.ino"
        - "examples/SMTP/Custom_Command/Basic_Auth/Basic_Auth.ino"
        - "examples/SMTP/Custom_Command/Custom_Auth/Custom_Auth.ino"
        - "examples/SMTP/Custom_Command/STARTTLS/STARTTLS.ino"

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install 3rd party dependecies
      run: | 
        pio lib -g install \
        https://github.com/mobizt/ESP-Mail-Client

    - name: update library
      run: |
        pio lib --global update
        
    - name: Run PlatformIO Examples
      run: |
        pio ci --board=d1_mini \
        --lib=examples/SMTP/Send_RFC822_Attachment/image.h \
        --lib=examples/SMTP/Send_Parallel_Attachment/data.h \
        --lib=examples/SMTP/Send_Attachment_Blob/blob_data.h
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}

  esp32:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: 
        - "examples/IMAP/Append_Message/Append_Message.ino"
        - "examples/IMAP/Custom_Character_Decoding/Custom_Character_Decoding.ino"
        - "examples/IMAP/Custom_Command/Append_Message/Append_Message.ino"
        - "examples/IMAP/Custom_Command/Idle/Idle.ino"
        - "examples/IMAP/Custom_Command/Basic_Auth/Basic_Auth.ino"
        - "examples/IMAP/Custom_Command/Custom_Auth/Custom_Auth.ino"
        - "examples/IMAP/Namespaces/Namespaces.ino"
        - "examples/IMAP/Get_Quota/Get_Quota.ino"
        - "examples/IMAP/ACL/ACL.ino"
        - "examples/IMAP/DataStreamCallback/DataStreamCallback.ino"
        - "examples/IMAP/Delete_Messages/Delete_Messages_List/Delete_Messages_List.ino"
        - "examples/IMAP/Delete_Messages/Delete_Messages_UIDs_Ranges/Delete_Messages_UIDs_Ranges.ino"
        - "examples/IMAP/Delete_Messages/Delete_Messages_Message_Numbers_Ranges/Delete_Messages_Message_Numbers_Ranges.ino"
        - "examples/IMAP/Copy_Messages/Copy_Messages_List/Copy_Messages_List.ino"
        - "examples/IMAP/Copy_Messages/Copy_Messages_UIDs_Ranges/Copy_Messages_UIDs_Ranges.ino"
        - "examples/IMAP/Copy_Messages/Copy_Messages_Message_Numbers_Ranges/Copy_Messages_Message_Numbers_Ranges.ino"
        - "examples/IMAP/Move_Messages/Move_Messages_List/Move_Messages_List.ino"
        - "examples/IMAP/Move_Messages/Move_Messages_UIDs_Ranges/Move_Messages_UIDs_Ranges.ino"
        - "examples/IMAP/Move_Messages/Move_Messages_Message_Numbers_Ranges/Move_Messages_Message_Numbers_Ranges.ino"
        - "examples/IMAP/Mailbox_Changes_Notification/Mailbox_Changes_Notification.ino"
        - "examples/IMAP/Read_Email_Access_Token/Read_Email_Access_Token.ino"
        - "examples/IMAP/Read_Single_Email/Read_Single_Email.ino"
        - "examples/IMAP/Read_Single_Email_Loop/Read_Single_Email_Loop.ino"
        - "examples/IMAP/Search_Emails/Search_Emails.ino"
        - "examples/IMAP/Set_Flags/Set_Flags_List/Set_Flags_List.ino"
        - "examples/IMAP/Set_Flags/Set_Flags_UIDs_Ranges/Set_Flags_UIDs_Ranges.ino"
        - "examples/IMAP/Set_Flags/Set_Flags_Message_Numbers_Ranges/Set_Flags_Message_Numbers_Ranges.ino"
        - "examples/IMAP/Read_Sequence_Set/Read_Sequence_Set.ino"
        - "examples/SMTP/Ethernet/ESP32/Send_Text/Send_Text.ino"
        - "examples/SMTP/Reply_Text/Reply_Text.ino"
        - "examples/SMTP/Send_HTML/Send_HTML.ino"
        - "examples/SMTP/Send_Access_Token/Send_Access_Token.ino"
        - "examples/SMTP/Send_Reuse_Session/Send_Reuse_Session.ino"
        - "examples/SMTP/Send_RFC822_Attachment/Send_RFC822_Attachment.ino"
        - "examples/SMTP/Send_Parallel_Attachment/Send_Parallel_Attachment.ino"
        - "examples/SMTP/Send_Attachment_Blob/Send_Attachment_Blob.ino"
        - "examples/SMTP/Send_Flash_Message_with_Inline_Image/Send_Flash_Message_with_Inline_Image.ino"
        - "examples/SMTP/Send_Text/Send_Text.ino"
        - "examples/SMTP/Send_Text_Flowed/Send_Text_Flowed.ino"
        - "examples/SMTP/Send_Enriched_Text/Send_Enriched_Text.ino"
        - "examples/SMTP/Send_Embedded_Message/Send_Embedded_Message.ino"
        - "examples/SMTP/Send_Attachment_File/Send_Attachment_File.ino"
        - "examples/SMTP/Custom_Command/Basic_Auth/Basic_Auth.ino"
        - "examples/SMTP/Custom_Command/Custom_Auth/Custom_Auth.ino"
        - "examples/SMTP/Custom_Command/STARTTLS/STARTTLS.ino"
        
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Install 3rd party dependecies
      run: | 
        pio lib -g install \
        https://github.com/mobizt/ESP-Mail-Client

    - name: update library
      run: |
        pio lib --global update

    - name: Run PlatformIO Examples
      run: |
        pio ci --board=esp32dev \
         --lib=examples/SMTP/Send_RFC822_Attachment/image.h \
         --lib=examples/SMTP/Send_Parallel_Attachment/data.h \
         --lib=examples/SMTP/Send_Attachment_Blob/blob_data.h

      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
